### PR TITLE
Ability to use (raw) html markup

### PR DESCRIPTION
**Pull request by doekman**
See issue https://github.com/stefanhaustein/notemplate/issues/6

Remarks:

- I could remove the closure, as it is not needed at the moment.
- I would like to add a license-comment to the code, as is mentioned at then end of the [LICENCE](https://github.com/stefanhaustein/notemplate/blob/master/LICENSE-file).

### CODE REVIEW

**Review by stefanhaustein — COMMENTED** [review]
I think for anything other than nodes / fragments, we should use appendText to escape the content. It will still be possible to append "raw" content by wrapping it in a raw() call, creating a fragment that will be appended unescaped.

**Comment by stefanhaustein** [comment]
Looks good but shouldn't we have a simpler example that just iterates a few use cases? We already have a complex example (todo) and it might be useful to have one that is very simple, purely focussing on the basics? 

I'd expect raw() as a function directly in tag more "common" than nested?

Could we use the non-template use case of raw to implement the template use case, avoiding the inner function definition?

wdyt?

**Comment by doekman** [comment]
> Looks good but shouldn't we have a simpler example that just iterates a few use cases? We already have a complex example (todo) and it might be useful to have one that is very simple, purely focussing on the basics?
> 
> I'd expect raw() as a function directly in tag more "common" than nested?

Yeah, I agree. Something like this?

    let nodes = [
        tag.p('He said: "this is so cool!".'),
        tag.p(raw('This is <code>code</code>.'))];

With "nested", do you mean this?

    let code = '<code>`code`</code';
    raw`markdown code: ${raw(code)}`;

I was a bit puzzled by this sentence, could you explain this?

> Could we use the non-template use case of raw to implement the template use case, avoiding the inner function definition?

About documentation: I like [this tutorial](https://pugsql.org/tutorial). The documentation is not perfect, but I like the tutorial describing all main features with examples. I imagine we could have a seperate `tutorial.md` document, with two chapters (tag and raw), and in each chapter incrementally describe

**Comment by stefanhaustein** [comment]
The new example looks good and easy to expand. The tutorial is even better.

"nested" -> yes

raw(x) Turns x into a HTML-Fragment. So for raw`, can't we use this internally to accumulate the content -- instead of having  "appendHtml"? Perhaps even use tag("div", list) where the list is the built from raw() of the string parts and the parameters directly, then throw away the div?

**Comment by stefanhaustein** [comment]
p.s. If you prefer we can also just go ahead and merge the current state and then take it from there...

**Comment by doekman** [comment]
Yeah, lets do that. I don't have my computer with me now, but feel free to finish up. I will make a start with the tutorial next week.

**Pull request merged**
