### PR TITLE
Element helpers

### PR DESCRIPTION
**Pull request by doekman**
I'm not sure if this change is fitting this library. However, I did want to share it with you and am curious what you think of it.

BTW: I've also changed the _todolist.html_ example a little bit.

### CODE REVIEW

**Comment by stefanhaustein** [comment]
I am not sure... I think I'd tend to drop the configurability and stick to one "fixed" name. On one hand, "tag" doesn't seem to be the technically correct term. On the other hand, it's short and everybody knows what it means. Did you consider any alternatives? "el"? Also, would it make sense to have something similar for attributes? In particular style and class?

**Comment by stefanhaustein** [comment]
p.s. how about the following:

- rename element to tag
- register the methods on tag; keep it simple -- no configuration
- keep element as a (deprecated) synonym for tag for now  for compatibility

**Comment by doekman** [comment]
This PR was inspired by base2 of Dean Edwards, which also had a helper method to add all html elements, but I can't find this in the source code at the moment.

I like the tag.p(...) idea. And tag("p", ...) will still work, right?

Configuration was only meant to not pollute the global namespace at default. This idea is much better.

Tag does feel like a better name than element. Slogan: no templates, just tags ;-)

Not sure if attribute helpers would be useful.

I might use this library for an internal work project in the next couple of months. The main reason to use this library is it's simple, and in 10 years it will still be understandable.

**Comment by stefanhaustein** [comment]
Cool can you update the PR accordingly? I'll promise I won't take 15 months again to respond O:)

**Comment by doekman** [comment]
No worries, everyone needs a rest once in a while.

About the documentation: do you tink the `tag(name, ...)` should be the preferred method in examples (as it is now) or should it be `tag.name(...)`?

**Comment by stefanhaustein** [comment]
I think it should be tag.name. May require some re-wording for the "single function" part before... But we can always do more cleanup in one or more followups...

**Comment by doekman** [comment]
The "singel function" part does need rewording, but I leave that to you.

Is this PR mergeable yet?

**Comment by stefanhaustein** [comment]
Done!  Thanks a lot!

**Pull request merged**
